Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.communicator = "ssh"
  config.vm.guest = "linux"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.name = 'cinp-demo'
  end

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.synced_folder "../src", "/opt/demo/src", create: true, :mount_options => ["ro"]
  config.vm.provision "file", source: "demo.service", destination: "/tmp/demo.service"
  config.vm.provision "shell", inline: <<-DEMO_CONFIG
set -e
set -x

apt-get update
apt-get install -y python3-django python3-werkzeug python3-pip python3-gunicorn python3-dateutil

pip3 install cinp

mkdir -p /opt/demo/db

/opt/demo/src/manage.py migrate
/opt/demo/src/manage.py createsuperuser --noinput --username=root --email=test@test.com
echo "from django.contrib.auth.models import User; u = User.objects.get(); u.set_password('root'); u.save()" | /opt/demo/src/manage.py shell

mv /tmp/demo.service /lib/systemd/system/demo.service

systemctl daemon-reload
systemctl enable demo.service
systemctl start demo.service

DEMO_CONFIG

end
